<?php 
 $matriz_norse = array
    (
        array(
            "Deuses",
            "Odin",
            "O pai dos deuses",
            "img/Odin.jpg",
			"Odin é considerado o pai de todos os deuses e governante de Asgard - o reino dos Æsir. Odin também é o deus da guerra e da batalha, da música, da mágica e poesia.

			Odin é filho de Borr e da gigante Bestla. Ele possui dois irmãos, chamados de Vili e Ve, e juntos eles criaram o mundo. Esse deus também possui pelo menos quatro filhos, 
			de diferentes parceiras, sendo que o mais conhecido deles é Thor.

			Entre os seus muitos poderes, Odin tem a capacidade de se transformar no que ele quiser, e sua voz é tão suave que tudo que ele diz é considerado como verdade.

			Segundo o mito, esse deus cavalga para a batalha em seu cavalo de oito pernas chamado Sleipnir. Em sua mão, ele empunha sua lança forjada pelo anão Gungnir,
			conhecida por nunca errar seu alvo."),
		array(
            "Deuses",
            "Frigg",
            "A deusa da fertilidade",
            "img/Frigg.jpg",
			"Frigg é a deusa-mãe, relacionada ao casamento, à família e à maternidade. Ela é a esposa de Odin, e governa ao seu lado sobre os Æsir, sendo a única autorizada a se 
			sentar com ele no trono e olhar através dos nove reinos.

			Frigg tem dois filhos com Odin, chamados Balder e Hod, e apesar de ter o poder da profecia, Frigg nunca revela o futuro à ninguém."),
		array(
            "Deuses",
            "Thor",
            "O deus do trovão",
            "img/Thor.jpg",
			"Thor é o Deus do Trovão, sendo encarregado de proteger tanto Asgard quanto Midgard, o reino dos humanos.

			Thor é filho de Odin e Jörð, a personificação da Terra. Ele é fisicamente o mais forte dos deuses Æsir, porém ele não é muito sábio, por isso os gigantes e outros deuses o 
			enganavam sempre que podiam.

			Esse deus costuma viajar em uma carruagem puxada pelas duas cabras, chamadas Tanngrisnir e Tanngnjóstr. As rodas de sua carruagem criam faíscas, que os humanos em Midgard 
			chamam de relâmpago."),
		array(
            "Deuses",
            "Loki",
            "O pai das mentiras",
            "img/Loki.jpg",
			"Loki é conhecido como o deus da trapaça, da mentira e traição. Considerado 'pai dos monstros', foi Loki quem gerou criaturas como o lobo Fenrir, a serpente Jörmungandr, 
			e Sleipnir, o cavalo de oito pernas de Odin. Ele também é o pai da Deusa Hel, a rainha do submundo.

			Devido à seus truques e mentiras, Loki não é considerado um dos Æsir. Ele pode assumir qualquer forma que quiser, e entre seus atos de maldade, ele causou a morte de Balder."),
		array(
            "Deuses",
            "Balder",
            "O deus da luz",
            "img/Balder.jpg",
			"Balder é o deus da luz e da pureza, considerado o mais amado entre os deuses e louvado por sua beleza e graça. Ele é filho de Odin e Frigg, e irmão gêmeo de Hod, o deus 
			cego.

			Um dos maiores mitos nórdicos conta a morte de Balder, quando Loki engana seu irmão Höðr. Segundo a lenda, após Balder sonhar com sua morte, Frigg exige que todos os 
			seres dos nove reinos jurassem nunca o machucar. Todos o fazem, menos o visco, e quando Loki descobre isso, ele convence Hod a atacar seu irmão com uma lança feita
			desta planta.

			O coração de Balder é perfurado e ele é levado para o mundo dos mortos. Porém, a mitologia nórdica conta que durante o Dia do Julgamento (Ragnarok), o submundo irá 
			se abrir. Então, Balder e Hod governarão juntos sob os nove reinos."),
		array(
            "Deuses",
            "Hela",
            "Deusa do submundo",
            "img/Hela.jpg",
			"Deusa do submundo, também chamado Helheim, Hel era filha de Loki e da gigante Angrboda. Era sua função julgar e decidir o destino das almas que entravam em seu reino, 
			e dentro dele, ela é mais poderosa até mesmo que o próprio Odin.

			A maioria dos poemas vikings a retrata como sendo parcialmente decomposta, possuindo um rosto e corpo de mulheres vivas, mas com as pernas de um cadáver.

			Hel é conhecida por ser uma deusa gananciosa e caprichosa."),
		array(
            "Deuses",
            "Freya",
            "A deusa do amor",
            "img/Freya.jpg",
			"Apesar de inicialmente pertencer à tribo Vanir, após a guerra ela foi enviada para Asgard, se tornando uma das Æsir. Freya tinha a capacidade de manipular os desejos e 
			a fortuna das pessoas, e também era considerada como a governante do reino da vida após a morte, Folkvang.

			Essa deusa era muitas vezes representada como buscadora do prazer e do desconhecido, sendo acusada por Loki de ter dormido com todos os deuses e elfos."),
        array(
            "Völuspá",
            "Sobre o Völuspá",
            "Do que se trata o poema mais conhecido da Edda Poética",
            "img/Voluspa.jpg",
			"Völuspá (A Profecia da Vidente) é o nome do primeiro e mais conhecido poema da Edda poética. Conta a história da criação do mundo e de seu iminente final,
			narrada por uma völva e dirigida a Odin. É uma das principais fontes primarias para o estudo da mitologia nórdica.
			
			A profecia começa com uma invocação a Odin, após a qual a vidente começa a relatar a história da criação do mundo de forma resumida. A vidente explica como
			conseguiu tal conhecimento, conhecendo assim a fonte da onisciência de Odin, e outros segredos dos deuses de Asgard. Menciona os acontecimentos presentes e 
			futuros, aludindo a muitos dos mitos nórdicos, como a morte de Balder e a prisão de Loki. Por último, a vidente fala do fim do mundo, Ragnarök, e de sua segunda 
			vinda."),
		array(
            "Völuspá",
            "Criação do mundo",
            "Primeira parte descrita pelo Völuspá",
            "img/criacao.jpg",
			"O poema começa com a völva pedindo silêncio para 'os filhos de Heimdallr' (seres humanos) e perguntando a Odin se ele quer que ela recite o conhecimento antigo.
			Ela diz que ela se lembra dos gigantes nascidos na antiguidade que criaram ela.

			Então ela começa a relatar o mito da criação; o mundo estava vazio até que os filhos de Borr levantaram a terra para fora do mar. Os Æsir, então, estabeleceram 
			ordem nos cosmos, encontrando lugares para o Sol, a Lua e as Estrelas, e, assim, começando o ciclo do dia e da noite. A era dourada, que seguiu os Æsir, tinha 
			ouro suficiente e eles, contentes, construíram templos e fizeram ferramentas. Mas, então, as três poderosas donzelas dos gigantes vieram de Jotunheim e a era de 
			ouro acabou. Assim, os Æsir criaram os anões, dos quais Durinn e Motsongir são os mais poderosos.

			Neste ponto, dez estrofes do poema acabaram e sucedem-se seis estrofes que contêm nomes de anões. Esta seção, às vezes chamada de Dvergatal (catálogo de anões), 
			é geralmente considerada uma interpolação e às vezes omitida por editores e tradutores."),
		array(
            "Völuspá",
            "Ragnarok",
            "O fim de tudo",
            "img/ragnarok.jpg",
			"Depois do Dvergatal, a criação do primeiro homem e da primeira mulher são recontados e a Yggdrasil, a árvore do mundo, é descrita. A vidente recorda os eventos que 
			levaram à primeira guerra, e o que ocorreu na luta entre os Æsir e os Vanir.

			A vidente, então, revela a Odin que ela sabe alguns de seus segredos, sobre o que ele sacrificou na busca do conhecimento. Ela conta-lhe que sabe onde seu olho está 
			escondido e como ele abriu mão dele em troca da sabedoria. Ela pergunta-lhe, em vários refrões, se ele entende, ou se quer ouvir mais.

			A vidente começa a descrever o assassinato de Balder, o mais justo dos deuses e o inimigo de Loki, e dos outros. Então ela profecia a destruição dos deuses onde o fogo
			e o dilúvio oprimem o céu e a terra quando os deuses lutarem sua última batalha com seus inimigos. Este é o 'destino final dos deuses' - Ragnarök. Ela descreve o chamado
			para a batalha, a morte de muitos dos deuses e como Odin é assassinado.

			Finalmente, um mundo belo e renascido vai levantar-se das cinzas da morte e destruição, onde Balder vai viver novamente neste novo mundo, onde a terra é abundante sem 
			clamar por sementes. Uma última estrofe descreve a repentina aparição do dragão Níðhöggr, trazendo corpos em suas asas, antes que a vidente acorde do transe."),
		array(
            "Mundos",
            "Asgard",
            "Mundo dos Aesir, o reino dos deuses, também conhecido como Godheim, Asgård, Asgaard e  Ásgarður.",
            "img/Asgard.jpg",
			"Os muros que cercam Asgard foram construídos por um gigante (identificado frequentemente e equivocadamente 
			como Hrimthurs). Como pagamento por seu trabalho, ele deveria receber a mão de Freya em casamento que é uma 
			das deusas mais belas e também Deusa da fertilidade, do sol e da lua. O acordo só valeria desde que o trabalho 
			fosse terminado dentro de seis dias. O gigante possuía um cavalo muito rápido e forte. Odin, que temia a perda 
			das maças douradas da juventude, ameaçou matar Loki se ele não salvasse os deuses do trato. O trapaceiro 
			transformou-se em uma égua e no último dia do acordo ele foi ao local, e seduziu o cavalo mágico do gigante, 
			Svadilfari. Deste modo, o trabalho não foi terminado a tempo, e os deuses conseguiram evadir-se do pagamento. 
			Loki em compensação pela 'distração' do cavalo do gigante pariu Sleipnir, o cavalo de 8 patas que posteriormente, foi dado a Odin como um presente.
			
			O guardião de Asgard é Heimdall. A planície de Hilda é o centro de Asgard. Os Æsir encontram-se lá para a discussão de temas importantes - os 
			deuses masculinos reúnem-se em um salão chamado Gladsheim, e as deusas em um salão chamado Vingolf. Eles também encontram-se diariamente no Well 
			of Urd, abaixo de Yggdrasil."),
		 array(
            "Mundos",
            "Midgard",
            "Reino dos Humanos, também conhecido como Miðgarðr, Miðgarðr, Midgård e Midjungards.",
            "img/Midgard.jpg",
			"O mundo de Midgard localiza-se no meio de Yggdrasil, cercado por um mundo de água ou oceano, cuja passagem é intransponível. O oceano é habitado
			pela enorme serpente marinha Jormungard, que circula todo o mar, formando um anel que impede a passagem de quaisquer seres ao agarrar sua própria 
			cauda. O nome original do que hoje é chamado Midgard era conhecido como Mannheim (lar dos homens), mas os primeiros pesquisadores da mitologia 
			confundiram a região como se fosse o castelo mais importante do local. Logo, Midgard, em algumas fontes antigas, era a mais imponente construção do
			mundo dos homens, Mannheim.

			Midgard é representada como sendo um mundo intermédio entre Asgard e Niflheim (respectivamente o paraíso e inferno nórdicos). De acordo com a lenda, 
			foi formada da carne e do sangue do gigante de gelo Ymir, a carne formando a terra; e o sangue, o oceano que a rodeia. Midgard será destruída na batalha 
			de Ragnarok, a batalha final, que terá lugar na planície de Vigrid. Nessa batalha, Jormungard, a gigantesca serpente que habita o oceano, irá levantar-se
			e envenenará a terra e o mar, fazendo com que as águas se lancem contra a terra, que será submergida, destruindo praticamente toda a vida em Midgard."),
		 array(
            "Mundos",
            "Jötunheim",
            "Reino dos Gigantes Comuns ou Gigantes da Montanha, por se localizar numa montanha, é também reino de outros seres mitológicos, como trolls.",
            "img/Jotunheim.jpg",
			"Jotunheim (Nórdico antigo “Jötunheimr ou Útgarðr”) é o lar dos gigantes (também chamado Jotuns). Eles são os inimigos jurados do Aesir. Jotunheim 
			consiste principalmente em rochas, terras selvagens e florestas densas, de modo que os gigantes vivem dos peixes nos rios e os animais na floresta, 
			porque não há terra fértil em Jotunheim. O mundo inteiro foi criado a partir do cadáver do primeiro gigante, chamado Ymir. Foi Odin e seus irmãos Vili e Ve, 
			que mataram Ymir.

			Os gigantes e os Aesir estão constantemente lutando, mas também acontece de vez em quando, que os assuntos amorosos ocorrerão. Odin, Thor e alguns outros, 
			tinham amantes que eram gigantes. Loki também veio de Jotunheim, mas ele foi aceito pelo Aesir e morou em Asgard. Jotunheim é separado de Asgard pelo rio Iving,
			que nunca congela. Encontra-se nas regiões nevadas nas margens mais externas do oceano. O bem da sabedoria de Mimir está em Jotunheim, sob a raiz Midgard da árvore 
			de cinzas Yggdrasil. A fortaleza de Utgard é tão grande que é difícil ver o topo. E o temido rei de Jotun, Utgard-Loki, vive. Utgard é esculpido a partir de blocos
			de neve e sincelos brilhantes."),
		 array(
            "Mundos",
            "Muspelheim",
            "Reino do Fogo, onde residem os Gigantes de Fogo.",
            "img/Muspelheim.jpg",
			"Muspelheim (Nórdico antigo “Múspellsheimr”) foi criado muito ao sul do mundo na mitologia nórdica. Muspelheim é um lugar quente queima, cheio de lava, chamas,
			faíscas e fuligem. Muspelheim é o lar de gigantes de fogo, demônios de fogo e governado pelo gigante Surtr. Ele é um inimigo jurado do Aesir. Surtr vai sair com
			sua espada flamejante em sua mão em Ragnarök “o fim do mundo” Surtr irá então atacar Asgard, “a casa dos deuses” e transformá-lo em um inferno flamejante."),
		 array(
            "Mundos",
            "Niflheim",
            "Reino de Gelo, onde residem os Gigantes de Gelo. Neste mundo também está localizado Helgardh, o domicílio dos mortos.",
            "img/Niflheim.jpg",
			"Niflheim (Nórdico antigo “Niðavellir”) e significa (“Casa da Névoa” ou “Mundo da Névoa”) é a região mais escura e mais fria do mundo, de acordo com a mitologia 
			nórdica. Niflheim é o primeiro dos nove mundos e Niflheim é colocado na região norte de Ginnungagap. O mais antigo dos três poços está localizado em Niflheim, 
			que se chama Hvergelmir “sopa de ebulição borbulhante” e é protegido pelo enorme dragão chamado Nidhug (Níðhöggr).

			Dizem que todos os rios frios provêm do bem chamado Hvergelmir, e é dito ser a fonte dos onze rios na mitologia nórdica. O bem Hvergelmir é a origem de todos 
			os vivos e o lugar onde todo ser vivo voltará. Elivagar “ondas de gelo” são os rios que existiram em Niflheim no início do mundo. Eles eram os rios que flutuavam 
			de Hvergelmir. A água de Elivagar caiu pelas montanhas até as planícies de Ginnungagap, onde se solidificou para gelo e gelo, que gradualmente formou uma camada muito 
			densa. Esta é a razão pela qual é muito frio nas planícies do norte. À medida que a árvore do mundo Yggdrasil começou a crescer, esticou uma de suas três grandes raízes
			até Niflheim e tirou água da primavera de Hvergelmir."),
		 array(
            "Mundos",
            "Vanaheim",
            "Reino dos Vanir, deuses da natureza.",
            "img/Vanaheim.jpg",
			"Vanaheim (Nórdico antigo “Vanaheimr”) é o lar dos deuses Vanir. Os deuses de Vanir são um antigo ramo dos deuses. Os Vanir são mestres da feitiçaria e da magia. 
			Eles também são amplamente reconhecidos por seu talento para prever o futuro. Ninguém sabe onde exatamente a terra, Vanaheim eu localizei, ou mesmo como parece. 
			Quando a guerra entre o Aesir eo Vanir terminou, três dos Vanir vieram morar em Asgard, Njord e seus filhos Freya e Freyr."),
		 array(
            "Mundos",
            "Álflheim",
            "Reino dos Elfos de luz.",
            "img/Alfheim.jpg",
			"Alfheim (Nórdico antigo “Álfheimr ou Ljósálfheimr”) está ao lado de Asgard no céu. Os duendes leves são criaturas bonitas. Eles são considerados os “anjos da guarda”
			O Deus Freyr, é o governante de Alfheim. Os duendes leves são deuses menores da natureza e da fertilidade; eles podem ajudar ou impedir os humanos com seu conhecimento 
			de poderes mágicos. Eles também apresentaram uma inspiração para a arte ou a música."),
         array(
            "Mundos",
            "Svartalfheim",
            "Reino dos Elfos escuros.",
            "img/Svartalfheim.jpg",
			"Svartalfheim (Nórdico antigo “Niðavellir ou Svartálfaheimr”) é o lar dos anões, eles vivem sob as rochas, nas cavernas e no subsolo. Hreidmar era o rei de Svartalfheim,
			Svartalfheim significa campos escuros. Os anões são mestres do artesanato. Os deuses de Asgard receberam muitos presentes poderosos. Como o martelo de Thor, o anel mágico
			Draupnir e também Gungnir, a lança de Odin."),   
		 array(
            "Mundos",
            "Helheim",
            "Reino dos Mortos, onde vão aqueles que morrem sem glória, por doenças ou por terem idade avançada.",
            "img/Helheim.jpg",
			"É no Hellheim que todos os mortos desonestos, ladrões, assassinos e aqueles que os deuses e deuses sentem não são corajosos o suficiente para ir a Valhalla ou Folkvangr.
			Helheim é governado pelas malvadas Godhas Hel, Helheim é um lugar muito sombrio e frio, e qualquer pessoa que eu chegar aqui nunca mais sentirá alegria e felicidade.
			Hel usará todos os mortos em seu reino em Ragnarök para atacar deuses e deusas, que serão o fim do mundo."),   
    ); 
?>